config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    resources :media_pages
  end

  match '/users/:user_id/media_pages/new(.:format)', to: 'media_pages#create', via: :post

  root 'media_pages#index'

end

app/models/media_page.rb
class MediaPage < ActiveRecord::Base
    belongs_to :user
    attr_accessible :name, :content, :user_id

    validates :name, presence: true
    validates :content, presence: true
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessible :name, :email, :password
    has_many :media_pages
    has_secure_password

    EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

    validates :name, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true, format: EMAIL_REGEX
    validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/media_pages_controller.rb
class MediaPagesController < ApplicationController
before_action :find_media_page, only: [:show, :update, :destroy]
    def index
        @media_pages = MediaPage.all
        @users = User.all
    end

    def show
    end

    def new
        @media_page = MediaPage.new
    end

    def create
        @user = User.find(params[:user_id])
        @media_page = MediaPage.new(media_page_params)
        if @media_page.save
            redirect_to @user
        else
            Rails.logger.info(@media_page.errors.inspect)
            render action: 'new'
        end
    end

    def update
    end

    def destroy
        @media_page.destroy
        redirect_to media_page
    end

    private
    def find_media_page
        @media_page = MediaPage.find(params[:id])
    end

    def media_page_params
        params.require(:media_page).permit(:name, :content).merge(:user_id => current_user.id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in user
            redirect_to user
        else
            flash[:danger] = 'Invalid email/password combination'
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:edit, :update, :show]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to @user
        else
            flash[:notice] = "Unable to sign up! Try again"
            render action: 'new'
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to @user
        else
            render action: 'edit'
        end
    end

    def show
    end

    private
    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_pages_helper.rb
module MediaPagesHelper
    def submit_content_btn
        if params[:action] == 'edit'
            return "Edit Media"
        else
            return "Add Media"
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def submit_user_btn
        if params[:action] == 'edit'
            return "Edit User"
        else
            return "Sign-up!"
        end
    end
end

app/views/layouts/_form.html.erb
<div>
<%= form_for(@user) do |f| %>
    Name: <%= f.text_field :name %> <br>
    Email: <%= f.text_field :email %> <br>
    Password: <%= f.password_field :password %> <br> <br>
    <%= f.submit :Signup %>
<% end %>

<% if @user.errors.any? %>
    <ul class="Signup_Errors">
        <% for message_error in @user.errors.full_messages %>
        <li>* <%= message_error %></li>
        <% end %>
    </ul>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediaCollections</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar"><% if logged_in? %>
    You are logged in as <%= link_to current_user.name, current_user %>. | <%= link_to "Log out", logout_path, method: "delete" %>
<% else %>
    <%= link_to "Log in", login_path %>
 Don't have an account? <strong><%= link_to "Sign-up here!", new_user_path %></strong><% end %></div>
<%= yield %>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

</body>
</html>

app/views/media_pages/_form.html.erb
<div>
<!-- https://github.com/rails/rails/issues/1769 -->
<!-- Have to specify url for the form because of this issue -->
<%= form_for @media_page, url: new_user_media_page_path do |f| %>
    Name: <%= f.text_field :name %> <br>
    Media content: <%= f.text_field :content %> <br> <br>
    <%= f.submit submit_content_btn %>
<% end %>

<% if @media_page.errors.any? %>
    <ul class="Signup_Errors">
        <% for message_error in @media_page.errors.full_messages %>
        <li>* <%= message_error %></li>
        <% end %>
    </ul>
<% end %>
</div>

app/views/media_pages/index.html.erb
<h1>Welcome to Media Collection</h1>
<p>You can use this tool to manage your media, links, etc. </p>

<% if logged_in? %>
    <%= link_to "GO TO YOUR MEDIA PAGE", current_user %>
<% else %>
    <h3>Log-in!</h3>
    <p><strong><%= link_to "Click here to log-in!", login_path %></strong></p>
    <h3>Don't have an account?</h3>
    <p><strong><%= link_to "Sign-up here!", new_user_path %></strong></p>
<% end %>
<br><br>
<h1>Current Users:</h1>
<% @users.each do |user| %>
<ul>
<li><%= link_to user.name, user %></li>
</ul>
<% end %>

app/views/media_pages/new.html.erb
New Media:

<%= render 'form' %>

app/views/users/_form.html.erb
<div>
<%= form_for(@user) do |f| %>
    Name: <%= f.text_field :name %> <br>
    Email: <%= f.text_field :email %> <br>
    Password: <%= f.password_field :password %> <br> <br>
    <%= f.submit submit_user_btn %>
<% end %>

<% if @user.errors.any? %>
    <ul class="Signup_Errors">
        <% for message_error in @user.errors.full_messages %>
        <li>* <%= message_error %></li>
        <% end %>
    </ul>
<% end %>
</div>

app/views/users/edit.html.erb
Edit user:

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Current Users:</h1>
<% @users.each do |user| %>
<ul>
<li><%= link_to user.name, user %></li>
</ul>
<% end %>
<h3>Want to sign up?</h3>
<%= link_to "Click Here!", new_user_path %>

app/views/users/new.html.erb
Create a new user:

<%= render 'form' %>

app/views/users/show.html.erb
<strong>Viewing user:</strong> <br>
<%= @user.name %> <br>
<%= @user.email %> <br> <br>

<strong>Users media:</strong>
<ul>
<% @user.media_pages.each do |media|%>
<li><%= media.name %> - <%= media.content %></li>
<% end %>
</ul>

<% if logged_in? %><%= link_to "Add Media to my profile!", new_user_media_page_path(@user) %>
<% else %>You can't add media to this profile.<% end %><br><br>

---- <br>
<%= link_to "Update User", edit_user_path %> <br>
<%= link_to "Home Page", root_path %>